In [ ]:
#A1-the purpose and advantages of NumPy in scientific computing and data analysis.
# enhancement of Python's capabilities for numerical operations

#1.numpy stands for numerical python. NumPy is essential for scientific computing and data analysis in Python.

#2. It supports large, multi-dimensional arrays and matrices.

#3. NumPy enables fast numerical operations through vectorization, reducing the need for Python loops.

#4. It integrates with other libraries like SciPy, Matplotlib, and pandas.

#5. Offers a wide range of mathematical functions, including linear algebra and statistics.

#6. Provides efficient memory management and low-level optimizations.

#7. NumPy’s core is written in C, ensuring high performance.

#8. Facilitates large-scale data manipulation and numerical computations.

#9. Simplifies complex mathematical operations with concise syntax.

#10. It’s a foundational tool for machine learning, data science, and engineering tasks.

In [1]:
#A2-Comparison of np.mean() and np.average() in NumPy:

#1. np.mean() calculates the arithmetic mean (average) of an array’s elements. It treats all elements equally, without weights.

#2. np.average() can calculate a weighted average, allowing you to assign different importance (weights) to each element.

#3. If no weights are given, np.average() works like np.mean().

#4. Use np.mean() when you want the simple average of all values.

#5. Use np.average() when you need to compute a weighted average.

#Example with np.mean():
import numpy as np
data = [1, 2, 3, 4, 5]
mean_value = np.mean(data)
print(mean_value)



3.0


In [2]:
# Example with np.average() (weighted average):

import numpy as np
data = [1, 2, 3, 4, 5]
weights = [1, 2, 3, 4, 5]
average_value = np.average(data, weights=weights)
print(average_value)


#In summary, use np.mean() for a simple average and np.average() when weights are needed.

3.6666666666666665


In [4]:
#A3- the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
#arrays
#Methods for Reversing a NumPy Array:
#For 1D array: Use [::-1] to reverse the array.

#For 2D array: Use [::-1, :] to reverse along rows (axis 0).

#For 2D array: Use [:, ::-1] to reverse along columns (axis 1).

#np.flip(array, axis): Flips along the specified axis.

#np.fliplr() and np.flipud(): Flip left-right and up-down for 2D arrays.

#Example of 1d array:
import numpy as np
arr_1d=np.array([1,2,3,4,5])
reversed_1d=arr_1d[::-1]
print(reversed_1d)

[5, 4, 3, 2, 1]


In [5]:
#example of 2d array
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
reverse_2d=arr_2d[::-1,:]
print(reverse_2d)


[[5 6]
 [3 4]
 [1 2]]


In [7]:
#A4- How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
#in memory management and performance.

#You can determine the data type of a NumPy array using the dtype attribute.

#1-Example: array.dtype returns the data type of elements in the array.

#2-Data types control how much memory each element occupies (e.g., int32 vs int64).

#3-Proper data type selection ensures memory efficiency, especially for large datasets.

#4-NumPy arrays store elements in contiguous memory blocks, improving access speed.

#5-Using the right data type reduces memory consumption (e.g., float32 uses less memory than float64).

#6-Data types also influence computation speed, as smaller types can be processed faster.

#7-Choosing the appropriate type avoids issues like overflow or precision loss in calculations.

#8-NumPy supports various types like integers, floats, and booleans for different needs.

#9-Efficient data type usage boosts overall performance in scientific computing tasks.

#example
arr=np.array([1,2,3,4,5],dtype=np.float64)
print(arr.dtype)






float64


In [10]:
#A5-ndarrays in NumPy and explain their key features. How do they differ from standard Python lists

#1-ndarray: Short for "N-dimensional array," it is a core data structure in NumPy that allows
#for efficient storage and manipulation of numerical data in multiple dimensions.

#2-Homogeneous Data: All elements in an ndarray must be of the same data type, leading to better performance and memory efficiency.

#3-Multidimensional: Unlike standard Python lists, which can be one-dimensional or nested, ndarrays can represent data in multiple dimensions (2D, 3D, etc.).

#4Vectorized Operations: ndarrays support element-wise operations, enabling faster computations without explicit loops.

#5-Memory Layout: ndarrays have a contiguous block of memory, which improves data access speed compared to Python lists,
# which can store pointers to separate objects.

#6-Rich Functionality: NumPy provides a wide range of functions for mathematical operations, reshaping, and broadcasting with ndarrays.

#7-Performance: NumPy's optimizations often lead to significantly faster execution for numerical tasks compared to Python lists.

#example
arr=np.array([[1,2],[3,4]])
print(arr)


[[1 2]
 [3 4]]


In [ ]:
#A6-Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

#1. Contiguous Memory: NumPy arrays use contiguous memory allocation, reducing cache misses and speeding up access times compared to Python lists,
#which store references to objects.

#2. Homogeneous Data Types: All elements in a NumPy array have the same data type,
# allowing for optimized memory usage and computational efficiency.

#3. Vectorization: NumPy allows for vectorized operations, enabling element-wise computations without the need for explicit loops,
#resulting in cleaner and faster code.

#4. Broadcasting: NumPy supports broadcasting, which allows operations on arrays of different shapes
# without the need for explicit replication, enhancing performance.

#5. Low-level Optimizations: NumPy leverages underlying libraries like BLAS and LAPACK,
# optimizing operations for speed through implementations in C and Fortran.

#7. Fast Aggregation Functions: NumPy provides highly optimized aggregation functions (e.g., `np.sum`, `np.mean`)
# that execute faster than equivalent Python list operations.

#8. Slicing and Indexing: NumPy's advanced slicing and indexing techniques allow
# for efficient data manipulation without the need for data copying.


#9. Parallel Processing: Many NumPy operations can be parallelized,
#further enhancing performance on multi-core systems.

#10. Scalability: NumPy is better suited for large datasets, making it the go-to choice for
#scientific computing, machine learning, and data analysis tasks.

In [13]:
#A7-Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and  output

#1-np.vstack(): Stacks arrays vertically (row-wise), adding new rows to the existing array while keeping the number of columns the same.

#2-np.hstack(): Stacks arrays horizontally (column-wise), adding new columns to the existing array while keeping the number of rows the same.

#3-Both functions require that the dimensions of the arrays match appropriately for the stacking operation

#4-Example of vstack()
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6]])
result_vstack= np.vstack((arr1,arr2))
print(result_vstack)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
#5-Example of hstack()
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5],[6]])
result_hstack=np.hstack((arr1,arr2))
print(result_hstack)

[[1 2 5]
 [3 4 6]]


In [15]:
#A8-Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various  array dimensions.

#1-np.fliplr(): Flips an array from left to right (horizontally), reversing the order of the columns for 2D arrays.

#2np.flipud(): Flips an array from up to down (vertically), reversing the order of the rows for 2D arrays.

#3-Both methods do not modify the original array; they return a new array with the applied transformations.

#4-For 1D arrays, both functions will not have any effect since there are no rows or columns to flip

#5-example
arr=np.array([[1,2,3],[4,5,6]])
print(np.fliplr(arr))

[[3 2 1]
 [6 5 4]]


In [16]:
arr=np.array([[1,2,3],[4,5,6]])
print(np.flipud(arr))

[[4 5 6]
 [1 2 3]]


In [18]:
#A9- Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits

#1-The array_split() method in NumPy divides an array into multiple sub-arrays along a specified axis,
#allowing for more flexibility than split().

#2-It can handle uneven splits, meaning sub-arrays can have different sizes
# when the original array's length is not perfectly divisible by the number of splits.

#3-You can specify the axis along which to split, with the default being axis 0 (rows).

#4-It returns a list of the resulting sub-arrays, making it easy to access and manipulate each part.

#5-Example
arr=np.array([1,2,3,4,5,6,7])
split=np.array_split(arr,3)
print(split)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [20]:
#A10- Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array  operations

#Vectorization
#1-Definition: Vectorization allows operations on entire NumPy arrays without explicit loops, enabling element-wise computations efficiently.

#2-Efficiency: It reduces execution time by utilizing optimized, low-level code, making operations faster compared to interpreted Python loops.

#3-example of vectorization
a=np.array([1,2,3])
b=np.array([4,5,6])
result=a+b
print(result)

[5 7 9]


In [21]:
#Broadcasting
#1-Definition: Broadcasting enables arithmetic operations on arrays of different shapes by automatically
#expanding the smaller array to match the larger array's shape.

#2-example of broadcasting
arr=np.array([1,2,3])
result=arr+5
print(result)


[6 7 8]


In [26]:
#PRACTICAL QUESTIONS

#A1- Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np
arr_3x3=np.random.randint(1,101,size=(3,3))
print (arr_3x3)    #original array

[[62 73 75]
 [43 89 22]
 [ 7 40 62]]


In [27]:
#interchange rows and columns
trans_arr=arr_3x3.T
print(trans_arr)  #transposed array

[[62 43  7]
 [73 89 40]
 [75 22 62]]


In [28]:
#A2- Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

arr_1d=np.arange(10)
arr_1d      #generating 1d numpy array with 10 elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr_2x5=arr_1d.reshape(2,5)   #reshaping it to 2x5 array
arr_2x5



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
arr_5x2=arr_1d.reshape(5,2)  #reshaping it to 5x2 array
arr_5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
#A3-Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

import numpy as np
arr_4x4=np.random.random((4,4))
arr_4x4   #4x4 array with random float values


array([[0.80891223, 0.12076048, 0.37246805, 0.02651964],
       [0.09816067, 0.63079266, 0.23096273, 0.59760451],
       [0.45094818, 0.79764143, 0.67109909, 0.46854111],
       [0.77470934, 0.90519917, 0.25051302, 0.67063861]])

In [34]:
arr_border=np.pad(arr_4x4,pad_width=1,mode='constant',constant_values=0)
arr_border  #6x6 array with a border of zeroes

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.80891223, 0.12076048, 0.37246805, 0.02651964,
        0.        ],
       [0.        , 0.09816067, 0.63079266, 0.23096273, 0.59760451,
        0.        ],
       [0.        , 0.45094818, 0.79764143, 0.67109909, 0.46854111,
        0.        ],
       [0.        , 0.77470934, 0.90519917, 0.25051302, 0.67063861,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [35]:
#A4- Using NumPy, create an array of integers from 10 to 60 with a step of 5.

array=np.arange(10,61,5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [36]:
#A5- Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

arr_str=np.array(['python','numpy','pandas'])
arr_str   #original array


array(['python', 'numpy', 'pandas'], dtype='<U6')

In [38]:
upp_arr=np.char.upper(arr_str)   #converting to uppercase
upp_arr

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [42]:
low_arr=np.char.lower(arr_str)  #converting to lowercase
low_arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [43]:
tit_arr=np.char.title(arr_str) #converting to titlecase
tit_arr


array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [44]:
#A6- Generate a NumPy array of words. Insert a space between each character of every word in the array.

words_arr=np.array(['python','numpy','pandas'])
words_arr  #original array

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [46]:
spaced_words_array=np.char.join(' ',words_arr)  #inserting a space bw each character of every word in the array
spaced_words_array

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [52]:
#A7- Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

add=arr1+arr2   #addition
print(add)


[[ 6  8]
 [10 12]]


In [53]:
sub=arr1-arr2    #subtraction
print(sub)

[[-4 -4]
 [-4 -4]]


In [54]:
mult=arr1*arr2   #multiplication
print(mult)

[[ 5 12]
 [21 32]]


In [55]:
div=arr1/arr2  #division
print(div)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [56]:
#A8- Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

id_matrix=np.eye(5)
id_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
diag_elements=np.diag(id_matrix)
print(diag_elements)

[1. 1. 1. 1. 1.]


In [ ]:
#A9- Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.
!pip install simpy
from simpy import isprime
rand_array=np.random.randint(0,1000,100)
rand_array
prime_numbers = [num for num in rand_array if isprime(num)]

print("Prime Numbers:", prime_numbers)

In [66]:
#A10- Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages.

# Create a NumPy array representing daily temperatures for 30 days
temperatures = np.random.randint(15, 35, size=30)

print("Daily Temperatures:", temperatures)


Daily Temperatures: [16 24 23 28 26 23 21 17 19 30 16 30 28 17 15 15 33 22 19 22 26 20 15 21
 27 26 23 27 27 19]


In [ ]:
weekly_averages = temperatures.reshape(4, 7).mean(axis=1)      #Reshape into 4 weeks (7 days per week) and calculate weekly averages
weekly_averages